services:
  solveitapp.api:
    image: ${DOCKER_REGISTRY-}solveitappapi
    build:
      context: .
      dockerfile: Solveit.Api/Dockerfile
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2

volumes:
  keycloak_data:
    external: true