services:
  solveitapp.api:
    image: ${DOCKER_REGISTRY-}solveitappapi
    build:
      context: .
      dockerfile: Solveit.Api/Dockerfile
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z

volumes:
  keycloak_data:
    external: true